import { User, Room, Schedule, AccessLog, DashboardStats } from "@/types";

// Mock data for the Room Find application
export const mockUsers: User[] = [
  {
    id: 1,
    name: "Dr. Maria Santos",
    email: "m.santos@university.edu",
    role: "faculty",
    department: "Computer Science",
    is_active: true,
    rfid_card: { id: 1, card_uid: "A1B2C3D4", user_id: 1, is_active: true, assigned_at: "2024-01-15T08:00:00Z" },
    created_at: "2024-01-10T08:00:00Z",
  },
  {
    id: 2,
    name: "Prof. Juan dela Cruz",
    email: "j.delacruz@university.edu",
    role: "faculty",
    department: "Mathematics",
    is_active: true,
    rfid_card: { id: 2, card_uid: "E5F6G7H8", user_id: 2, is_active: true, assigned_at: "2024-01-16T08:00:00Z" },
    created_at: "2024-01-11T08:00:00Z",
  },
  {
    id: 3,
    name: "Admin User",
    email: "admin@university.edu",
    role: "admin",
    department: "Administration",
    is_active: true,
    created_at: "2024-01-01T08:00:00Z",
  },
  {
    id: 4,
    name: "Dr. Ana Reyes",
    email: "a.reyes@university.edu",
    role: "faculty",
    department: "Physics",
    is_active: true,
    rfid_card: { id: 3, card_uid: "I9J0K1L2", user_id: 4, is_active: true, assigned_at: "2024-02-01T08:00:00Z" },
    created_at: "2024-01-12T08:00:00Z",
  },
  {
    id: 5,
    name: "Prof. Carlos Mendoza",
    email: "c.mendoza@university.edu",
    role: "faculty",
    department: "Engineering",
    is_active: false,
    created_at: "2024-01-13T08:00:00Z",
  },
];

export const mockRooms: Room[] = [
  {
    id: 1,
    room_code: "CS-101",
    name: "Computer Lab 1",
    building: "Science Building",
    floor: 1,
    capacity: 40,
    status: "available",
    features: ["Projector", "AC", "Computers"],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-06-10T09:15:00Z",
  },
  {
    id: 2,
    room_code: "CS-102",
    name: "Computer Lab 2",
    building: "Science Building",
    floor: 1,
    capacity: 40,
    status: "occupied",
    current_user_id: 1,
    current_user_name: "Dr. Maria Santos",
    features: ["Projector", "AC", "Computers"],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-06-10T10:30:00Z",
  },
  {
    id: 3,
    room_code: "MATH-201",
    name: "Math Lecture Hall",
    building: "Academic Building",
    floor: 2,
    capacity: 60,
    status: "available",
    features: ["Projector", "AC", "Whiteboard"],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-06-10T08:00:00Z",
  },
  {
    id: 4,
    room_code: "PHYS-301",
    name: "Physics Lab",
    building: "Science Building",
    floor: 3,
    capacity: 30,
    status: "maintenance",
    features: ["Lab Equipment", "AC"],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-06-09T14:00:00Z",
  },
  {
    id: 5,
    room_code: "ENG-401",
    name: "Engineering Workshop",
    building: "Engineering Building",
    floor: 4,
    capacity: 25,
    status: "occupied",
    current_user_id: 4,
    current_user_name: "Dr. Ana Reyes",
    features: ["Workshop Tools", "AC"],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-06-10T11:00:00Z",
  },
  {
    id: 6,
    room_code: "LIB-101",
    name: "Library Study Room",
    building: "Library",
    floor: 1,
    capacity: 20,
    status: "available",
    features: ["AC", "Whiteboard"],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-06-10T07:30:00Z",
  },
];

export const mockSchedules: Schedule[] = [
  {
    id: 1,
    room_id: 1,
    room_code: "CS-101",
    room_name: "Computer Lab 1",
    user_id: 1,
    faculty_name: "Dr. Maria Santos",
    subject: "Introduction to Programming",
    section: "CS-1A",
    day_of_week: "Monday",
    time_start: "08:00",
    time_end: "10:00",
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: 2,
    room_id: 2,
    room_code: "CS-102",
    room_name: "Computer Lab 2",
    user_id: 1,
    faculty_name: "Dr. Maria Santos",
    subject: "Data Structures",
    section: "CS-2B",
    day_of_week: "Tuesday",
    time_start: "10:00",
    time_end: "12:00",
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: 3,
    room_id: 3,
    room_code: "MATH-201",
    room_name: "Math Lecture Hall",
    user_id: 2,
    faculty_name: "Prof. Juan dela Cruz",
    subject: "Calculus I",
    section: "MATH-1A",
    day_of_week: "Monday",
    time_start: "09:00",
    time_end: "11:00",
    created_at: "2024-01-16T00:00:00Z",
  },
  {
    id: 4,
    room_id: 5,
    room_code: "ENG-401",
    room_name: "Engineering Workshop",
    user_id: 4,
    faculty_name: "Dr. Ana Reyes",
    subject: "Physics Laboratory",
    section: "PHYS-2A",
    day_of_week: "Wednesday",
    time_start: "13:00",
    time_end: "16:00",
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: 5,
    room_id: 1,
    room_code: "CS-101",
    room_name: "Computer Lab 1",
    user_id: 2,
    faculty_name: "Prof. Juan dela Cruz",
    subject: "Discrete Mathematics",
    section: "CS-2A",
    day_of_week: "Thursday",
    time_start: "14:00",
    time_end: "16:00",
    created_at: "2024-01-16T00:00:00Z",
  },
];

export const mockAccessLogs: AccessLog[] = [
  {
    id: 1,
    user_id: 1,
    user_name: "Dr. Maria Santos",
    room_id: 2,
    room_code: "CS-102",
    room_name: "Computer Lab 2",
    card_uid: "A1B2C3D4",
    action: "check_in",
    timestamp: "2024-06-10T10:28:45Z",
  },
  {
    id: 2,
    user_id: 4,
    user_name: "Dr. Ana Reyes",
    room_id: 5,
    room_code: "ENG-401",
    room_name: "Engineering Workshop",
    card_uid: "I9J0K1L2",
    action: "check_in",
    timestamp: "2024-06-10T10:58:12Z",
  },
  {
    id: 3,
    user_id: 2,
    user_name: "Prof. Juan dela Cruz",
    room_id: 3,
    room_code: "MATH-201",
    room_name: "Math Lecture Hall",
    card_uid: "E5F6G7H8",
    action: "check_in",
    timestamp: "2024-06-10T09:02:33Z",
  },
  {
    id: 4,
    user_id: 2,
    user_name: "Prof. Juan dela Cruz",
    room_id: 3,
    room_code: "MATH-201",
    room_name: "Math Lecture Hall",
    card_uid: "E5F6G7H8",
    action: "check_out",
    timestamp: "2024-06-10T11:05:18Z",
  },
  {
    id: 5,
    user_id: 1,
    user_name: "Dr. Maria Santos",
    room_id: 1,
    room_code: "CS-101",
    room_name: "Computer Lab 1",
    card_uid: "A1B2C3D4",
    action: "check_in",
    timestamp: "2024-06-10T08:01:22Z",
  },
  {
    id: 6,
    user_id: 1,
    user_name: "Dr. Maria Santos",
    room_id: 1,
    room_code: "CS-101",
    room_name: "Computer Lab 1",
    card_uid: "A1B2C3D4",
    action: "check_out",
    timestamp: "2024-06-10T09:58:44Z",
  },
  {
    id: 7,
    user_id: 4,
    user_name: "Dr. Ana Reyes",
    room_id: 4,
    room_code: "PHYS-301",
    room_name: "Physics Lab",
    card_uid: "I9J0K1L2",
    action: "check_in",
    timestamp: "2024-06-09T13:00:05Z",
  },
  {
    id: 8,
    user_id: 4,
    user_name: "Dr. Ana Reyes",
    room_id: 4,
    room_code: "PHYS-301",
    room_name: "Physics Lab",
    card_uid: "I9J0K1L2",
    action: "check_out",
    timestamp: "2024-06-09T15:30:44Z",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalRooms: 6,
  availableRooms: 3,
  occupiedRooms: 2,
  maintenanceRooms: 1,
  totalUsers: 5,
  activeUsers: 4,
  todayCheckIns: 4,
  activeSchedules: 5,
};
